// pages/inventory.vue
<script setup lang="ts">
definePageMeta({ layout: "dashboard" });

const { addToast } = useToast();
const { data: inventory, refresh } = await useFetch("/api/inventory");

const totalUnits = computed(() =>
  inventory.value?.reduce((sum, i) => sum + i.unitsAvailable, 0) ?? 0
);
const lowStockCount = computed(() =>
  inventory.value?.filter((i) => i.unitsAvailable < i.minimumStock).length ?? 0
);
const outOfStock = computed(() =>
  inventory.value?.filter((i) => i.unitsAvailable === 0).length ?? 0
);

const editingId = ref<string | null>(null);
const editForm = reactive({ unitsAvailable: 0, minimumStock: 5 });

const startEdit = (item: any) => {
  editingId.value = item.id;
  editForm.unitsAvailable = item.unitsAvailable;
  editForm.minimumStock = item.minimumStock;
};

const saveEdit = async (id: string) => {
  try {
    await $fetch("/api/inventory", {
      method: "PATCH",
      body: { id, ...editForm },
    });
    addToast("Inventory updated");
    editingId.value = null;
    await refresh();
  } catch (e: any) {
    addToast(e?.data?.message || "Failed to update", "error");
  }
};

const formatDate = (date: string) => new Date(date).toLocaleDateString();
</script>

<template>
  <div>
    <h1 class="text-2xl font-bold text-gray-900 mb-1">Blood Inventory</h1>
    <p class="text-sm text-gray-500 mb-6">Monitor and manage blood stock levels</p>

    <!-- Summary Cards -->
    <div class="grid grid-cols-3 gap-4 mb-6">
      <div class="bg-white rounded-xl border p-4">
        <p class="text-sm text-gray-500">Total Units</p>
        <p class="text-3xl font-bold text-red-600">{{ totalUnits }}</p>
      </div>
      <div class="bg-white rounded-xl border p-4">
        <p class="text-sm text-gray-500">Low Stock Types</p>
        <p class="text-3xl font-bold text-yellow-600">{{ lowStockCount }}</p>
      </div>
      <div class="bg-white rounded-xl border p-4">
        <p class="text-sm text-gray-500">Out of Stock</p>
        <p class="text-3xl font-bold text-red-600">{{ outOfStock }}</p>
      </div>
    </div>

    <!-- Blood Type Cards -->
    <div class="grid grid-cols-8 gap-3 mb-6">
      <div
        v-for="item in inventory"
        :key="item.id"
        class="bg-white rounded-xl border p-3 text-center"
      >
        <p class="text-xs text-gray-500">{{ item.bloodType }}{{ item.rhFactor }}</p>
        <p
          class="text-2xl font-bold"
          :class="item.unitsAvailable < item.minimumStock ? 'text-red-600' : 'text-green-600'"
        >
          {{ item.unitsAvailable }}
        </p>
        <p class="text-xs text-gray-400">units</p>
      </div>
    </div>

    <!-- Inventory Table -->
    <div class="bg-white rounded-xl border">
      <div class="p-4 border-b">
        <h2 class="font-medium text-sm">Inventory Details</h2>
      </div>
      <table class="w-full text-sm">
        <thead class="bg-gray-50 border-b">
          <tr>
            <th class="text-left px-4 py-3 font-medium text-gray-600">Blood Type</th>
            <th class="text-left px-4 py-3 font-medium text-gray-600">Units Available</th>
            <th class="text-left px-4 py-3 font-medium text-gray-600">Minimum Stock</th>
            <th class="text-left px-4 py-3 font-medium text-gray-600">Status</th>
            <th class="text-left px-4 py-3 font-medium text-gray-600">Last Updated</th>
            <th class="text-left px-4 py-3 font-medium text-gray-600">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y">
          <tr v-for="item in inventory" :key="item.id" class="hover:bg-gray-50">
            <td class="px-4 py-3 font-medium">{{ item.bloodType }}{{ item.rhFactor }}</td>
            <td class="px-4 py-3">
              <input
                v-if="editingId === item.id"
                v-model.number="editForm.unitsAvailable"
                type="number"
                class="w-20 px-2 py-1 border rounded text-sm"
              />
              <span v-else>{{ item.unitsAvailable }}</span>
            </td>
            <td class="px-4 py-3">
              <input
                v-if="editingId === item.id"
                v-model.number="editForm.minimumStock"
                type="number"
                class="w-20 px-2 py-1 border rounded text-sm"
              />
              <span v-else>{{ item.minimumStock }}</span>
            </td>
            <td class="px-4 py-3">
              <span
                class="px-2 py-0.5 rounded text-xs font-medium"
                :class="item.unitsAvailable < item.minimumStock
                  ? 'bg-red-100 text-red-700'
                  : 'bg-green-100 text-green-700'"
              >
                {{ item.unitsAvailable < item.minimumStock ? 'Low Stock' : 'In Stock' }}
              </span>
            </td>
            <td class="px-4 py-3 text-gray-600">{{ formatDate(item.lastUpdated) }}</td>
            <td class="px-4 py-3">
              <div v-if="editingId === item.id" class="flex gap-2">
                <button @click="saveEdit(item.id)" class="text-xs bg-green-50 text-green-700 px-3 py-1 rounded border border-green-200 hover:bg-green-100">Save</button>
                <button @click="editingId = null" class="text-xs bg-gray-50 text-gray-600 px-3 py-1 rounded border hover:bg-gray-100">Cancel</button>
              </div>
              <button v-else @click="startEdit(item)" class="text-xs bg-gray-50 text-gray-600 px-3 py-1 rounded border hover:bg-gray-100">Edit</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// src/app/(dashboard)/inventory/page.tsx
import { prisma } from "@/lib/db";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { InventoryActions } from "./inventory-actions";

export default async function InventoryPage() {
  const inventory = await prisma.bloodInventory.findMany({
    orderBy: [{ bloodType: "asc" }, { rhFactor: "asc" }],
  });

  const totalUnits = inventory.reduce((sum, inv) => sum + inv.unitsAvailable, 0);
  const lowStock = inventory.filter((inv) => inv.unitsAvailable <= inv.minimumStock);
  const criticalStock = inventory.filter((inv) => inv.unitsAvailable === 0);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Blood Inventory</h1>
        <p className="text-muted-foreground">Monitor and manage blood stock levels</p>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Total Units</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-red-600">{totalUnits}</div>
          </CardContent>
        </Card>
        <Card className={lowStock.length > 0 ? "border-yellow-200" : ""}>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Low Stock Types</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-yellow-600">{lowStock.length}</div>
          </CardContent>
        </Card>
        <Card className={criticalStock.length > 0 ? "border-red-200" : ""}>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Out of Stock</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-red-600">{criticalStock.length}</div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-4 grid-cols-4 md:grid-cols-8">
        {inventory.map((inv) => {
          const isLow = inv.unitsAvailable <= inv.minimumStock;
          const isEmpty = inv.unitsAvailable === 0;
          return (
            <Card
              key={inv.id}
              className={
                isEmpty
                  ? "border-red-300 bg-red-50"
                  : isLow
                    ? "border-yellow-300 bg-yellow-50"
                    : ""
              }
            >
              <CardContent className="p-4 text-center">
                <div className="text-xl font-bold">
                  {inv.bloodType}{inv.rhFactor}
                </div>
                <div className="text-3xl font-bold mt-1 text-red-600">
                  {inv.unitsAvailable}
                </div>
                <div className="text-xs text-muted-foreground">units</div>
                {isLow && (
                  <Badge variant="outline" className="mt-2 text-xs">
                    {isEmpty ? "Empty" : "Low"}
                  </Badge>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Inventory Details</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Blood Type</TableHead>
                <TableHead>Units Available</TableHead>
                <TableHead>Minimum Stock</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Last Updated</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {inventory.map((inv) => (
                <TableRow key={inv.id}>
                  <TableCell className="font-mono font-bold">
                    {inv.bloodType}{inv.rhFactor}
                  </TableCell>
                  <TableCell className="text-lg font-bold">{inv.unitsAvailable}</TableCell>
                  <TableCell>{inv.minimumStock}</TableCell>
                  <TableCell>
                    {inv.unitsAvailable === 0 ? (
                      <Badge variant="destructive">Out of Stock</Badge>
                    ) : inv.unitsAvailable <= inv.minimumStock ? (
                      <Badge className="bg-yellow-100 text-yellow-800 hover:bg-yellow-100">Low Stock</Badge>
                    ) : (
                      <Badge className="bg-green-100 text-green-800 hover:bg-green-100">In Stock</Badge>
                    )}
                  </TableCell>
                  <TableCell>
                    {new Date(inv.lastUpdated).toLocaleDateString()}
                  </TableCell>
                  <TableCell>
                    <InventoryActions inventory={inv} />
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
