// pages/donors/index.vue
<script setup lang="ts">
import { Plus } from "lucide-vue-next";

definePageMeta({ layout: "dashboard" });

const { data: donors, refresh } = await useFetch("/api/donors");

const formatDate = (date: string | null) => {
  if (!date) return "Never";
  return new Date(date).toLocaleDateString();
};
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Donors</h1>
        <p class="text-sm text-gray-500">Manage blood donors</p>
      </div>
      <NuxtLink
        to="/donors/new"
        class="flex items-center gap-2 bg-red-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-red-700 transition-colors"
      >
        <Plus class="w-4 h-4" />
        Register Donor
      </NuxtLink>
    </div>

    <div class="bg-white rounded-xl border">
      <div class="p-4 border-b">
        <h2 class="font-medium text-sm">All Donors ({{ donors?.length ?? 0 }})</h2>
      </div>
      <div v-if="donors?.length" class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-gray-50 border-b">
            <tr>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Name</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Blood Type</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Phone</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Status</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Last Donation</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y">
            <tr v-for="donor in donors" :key="donor.id" class="hover:bg-gray-50">
              <td class="px-4 py-3 font-medium">{{ donor.firstName }} {{ donor.lastName }}</td>
              <td class="px-4 py-3">
                <span class="px-2 py-0.5 bg-red-50 text-red-700 rounded text-xs font-medium border border-red-200">
                  {{ donor.bloodType }}{{ donor.rhFactor }}
                </span>
              </td>
              <td class="px-4 py-3 text-gray-600">{{ donor.phone }}</td>
              <td class="px-4 py-3">
                <span
                  class="px-2 py-0.5 rounded text-xs font-medium"
                  :class="{
                    'bg-green-100 text-green-700': donor.status === 'ACTIVE',
                    'bg-gray-100 text-gray-600': donor.status === 'INACTIVE',
                    'bg-yellow-100 text-yellow-700': donor.status === 'DEFERRED',
                  }"
                >
                  {{ donor.status }}
                </span>
              </td>
              <td class="px-4 py-3 text-gray-600">{{ formatDate(donor.lastDonation) }}</td>
              <td class="px-4 py-3">
                <NuxtLink :to="`/donors/${donor.id}`" class="text-red-600 hover:text-red-800 text-xs font-medium">
                  View
                </NuxtLink>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div v-else class="p-12 text-center text-gray-400 text-sm">
        No donors registered yet.
      </div>
    </div>
  </div>
</template>

// src/app/(dashboard)/donors/page.tsx
import Link from "next/link";
import { prisma } from "@/lib/db";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Plus } from "lucide-react";

export default async function DonorsPage() {
  const donors = await prisma.donor.findMany({
    orderBy: { createdAt: "desc" },
    include: { donations: { take: 1, orderBy: { donationDate: "desc" } } },
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Donors</h1>
          <p className="text-muted-foreground">Manage blood donor records</p>
        </div>
        <Link href="/donors/new">
          <Button className="bg-red-600 hover:bg-red-700">
            <Plus className="mr-2 h-4 w-4" />
            Register Donor
          </Button>
        </Link>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>All Donors ({donors.length})</CardTitle>
        </CardHeader>
        <CardContent>
          {donors.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">
              No donors registered yet. Click &quot;Register Donor&quot; to add one.
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead>Blood Type</TableHead>
                  <TableHead>Phone</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Last Donation</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {donors.map((donor) => (
                  <TableRow key={donor.id}>
                    <TableCell className="font-medium">
                      {donor.firstName} {donor.lastName}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="font-mono">
                        {donor.bloodType}{donor.rhFactor}
                      </Badge>
                    </TableCell>
                    <TableCell>{donor.phone}</TableCell>
                    <TableCell>
                      <StatusBadge status={donor.status} />
                    </TableCell>
                    <TableCell>
                      {donor.lastDonation
                        ? new Date(donor.lastDonation).toLocaleDateString()
                        : "Never"}
                    </TableCell>
                    <TableCell>
                      <Link href={`/donors/${donor.id}`}>
                        <Button variant="outline" size="sm">
                          View
                        </Button>
                      </Link>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const colors: Record<string, string> = {
    ACTIVE: "bg-green-100 text-green-800",
    INACTIVE: "bg-gray-100 text-gray-800",
    DEFERRED: "bg-yellow-100 text-yellow-800",
  };
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-1 text-xs font-medium ${colors[status] || "bg-gray-100 text-gray-800"}`}
    >
      {status}
    </span>
  );
}
