// pages/dashboard.vue
<script setup lang="ts">
import { Heart, Droplets, Package, FileText } from "lucide-vue-next";

definePageMeta({ layout: "dashboard" });

const { data: stats, refresh } = await useFetch("/api/dashboard/stats");
</script>

<template>
  <div>
    <h1 class="text-2xl font-bold text-gray-900 mb-1">Dashboard</h1>
    <p class="text-sm text-gray-500 mb-6">
      Welcome back, {{ useAuth().user.value?.name }}
    </p>

    <!-- Stats Cards -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
      <div class="bg-white rounded-xl border p-4">
        <div class="flex items-center justify-between mb-2">
          <span class="text-sm text-gray-500">Total Donors</span>
          <Heart class="w-4 h-4 text-red-400" />
        </div>
        <p class="text-2xl font-bold">{{ stats?.donorCount ?? 0 }}</p>
      </div>
      <div class="bg-white rounded-xl border p-4">
        <div class="flex items-center justify-between mb-2">
          <span class="text-sm text-gray-500">Total Donations</span>
          <Droplets class="w-4 h-4 text-red-400" />
        </div>
        <p class="text-2xl font-bold">{{ stats?.donationCount ?? 0 }}</p>
      </div>
      <div class="bg-white rounded-xl border p-4">
        <div class="flex items-center justify-between mb-2">
          <span class="text-sm text-gray-500">Blood Units Available</span>
          <Package class="w-4 h-4 text-red-400" />
        </div>
        <p class="text-2xl font-bold">{{ stats?.totalUnits ?? 0 }}</p>
      </div>
      <div class="bg-white rounded-xl border p-4">
        <div class="flex items-center justify-between mb-2">
          <span class="text-sm text-gray-500">Pending Requests</span>
          <FileText class="w-4 h-4 text-red-400" />
        </div>
        <p class="text-2xl font-bold">{{ stats?.pendingRequests ?? 0 }}</p>
      </div>
    </div>

    <!-- Blood Inventory + Recent Donations -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div class="bg-white rounded-xl border p-5">
        <h2 class="font-semibold text-gray-900 mb-4">Blood Inventory</h2>
        <div class="grid grid-cols-4 gap-3">
          <div
            v-for="item in stats?.inventory"
            :key="item.id"
            class="text-center p-3 bg-gray-50 rounded-lg"
          >
            <p class="text-xs text-gray-500">{{ item.bloodType }}{{ item.rhFactor }}</p>
            <p
              class="text-xl font-bold"
              :class="item.unitsAvailable < item.minimumStock ? 'text-red-600' : 'text-green-600'"
            >
              {{ item.unitsAvailable }}
            </p>
            <p class="text-xs text-gray-400">units</p>
          </div>
        </div>
      </div>

      <div class="bg-white rounded-xl border p-5">
        <h2 class="font-semibold text-gray-900 mb-4">Recent Donations</h2>
        <div v-if="stats?.recentDonations?.length" class="space-y-3">
          <div
            v-for="donation in stats.recentDonations"
            :key="donation.id"
            class="flex items-center justify-between text-sm"
          >
            <span class="text-gray-700">
              {{ donation.donor.firstName }} {{ donation.donor.lastName }}
            </span>
            <div class="flex items-center gap-2">
              <span class="px-2 py-0.5 bg-gray-100 rounded text-xs">
                {{ donation.bloodType }}{{ donation.rhFactor }}
              </span>
              <span
                class="px-2 py-0.5 rounded text-xs font-medium"
                :class="{
                  'bg-yellow-100 text-yellow-700': donation.status === 'COLLECTED',
                  'bg-blue-100 text-blue-700': donation.status === 'TESTED',
                  'bg-green-100 text-green-700': donation.status === 'APPROVED',
                  'bg-red-100 text-red-700': donation.status === 'REJECTED',
                }"
              >
                {{ donation.status }}
              </span>
            </div>
          </div>
        </div>
        <p v-else class="text-sm text-gray-400 text-center py-4">No donations yet.</p>
      </div>
    </div>
  </div>
</template>

// src/app/(dashboard)/dashboard/page.tsx
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Heart, Droplets, Package, ClipboardList, AlertTriangle } from "lucide-react";

export default async function DashboardPage() {
  const session = await getServerSession(authOptions);

  const [donorCount, donationCount, requestCount, inventory, recentDonations, pendingRequests] =
    await Promise.all([
      prisma.donor.count(),
      prisma.donation.count(),
      prisma.bloodRequest.count({ where: { status: "PENDING" } }),
      prisma.bloodInventory.findMany({ orderBy: { bloodType: "asc" } }),
      prisma.donation.findMany({
        take: 5,
        orderBy: { donationDate: "desc" },
        include: { donor: true },
      }),
      prisma.bloodRequest.findMany({
        where: { status: "PENDING" },
        take: 5,
        orderBy: { createdAt: "desc" },
      }),
    ]);

  const totalUnits = inventory.reduce((sum, inv) => sum + inv.unitsAvailable, 0);
  const lowStockItems = inventory.filter((inv) => inv.unitsAvailable <= inv.minimumStock);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Dashboard</h1>
        <p className="text-muted-foreground">
          Welcome back, {session?.user?.name}
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Total Donors</CardTitle>
            <Heart className="h-4 w-4 text-red-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{donorCount}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Total Donations</CardTitle>
            <Droplets className="h-4 w-4 text-red-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{donationCount}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Blood Units Available</CardTitle>
            <Package className="h-4 w-4 text-red-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalUnits}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Pending Requests</CardTitle>
            <ClipboardList className="h-4 w-4 text-red-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{requestCount}</div>
          </CardContent>
        </Card>
      </div>

      {lowStockItems.length > 0 && (
        <Card className="border-yellow-200 bg-yellow-50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-yellow-800">
              <AlertTriangle className="h-5 w-5" />
              Low Stock Alert
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {lowStockItems.map((item) => (
                <Badge key={item.id} variant="outline" className="border-yellow-300 text-yellow-800">
                  {item.bloodType}{item.rhFactor}: {item.unitsAvailable} units (min: {item.minimumStock})
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Blood Inventory</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-4 gap-3">
              {inventory.map((inv) => (
                <div
                  key={inv.id}
                  className={cn(
                    "rounded-lg p-3 text-center",
                    inv.unitsAvailable <= inv.minimumStock
                      ? "bg-red-50 border border-red-200"
                      : "bg-gray-50"
                  )}
                >
                  <div className="text-lg font-bold">
                    {inv.bloodType}{inv.rhFactor}
                  </div>
                  <div className="text-2xl font-bold text-red-600">{inv.unitsAvailable}</div>
                  <div className="text-xs text-muted-foreground">units</div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Recent Donations</CardTitle>
          </CardHeader>
          <CardContent>
            {recentDonations.length === 0 ? (
              <p className="text-sm text-muted-foreground">No donations recorded yet.</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Donor</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {recentDonations.map((donation) => (
                    <TableRow key={donation.id}>
                      <TableCell className="text-sm">
                        {donation.donor.firstName} {donation.donor.lastName}
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline">
                          {donation.bloodType}{donation.rhFactor}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <StatusBadge status={donation.status} />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </div>

      {pendingRequests.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Pending Blood Requests</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Patient</TableHead>
                  <TableHead>Blood Type</TableHead>
                  <TableHead>Units</TableHead>
                  <TableHead>Urgency</TableHead>
                  <TableHead>Hospital</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {pendingRequests.map((request) => (
                  <TableRow key={request.id}>
                    <TableCell>{request.patientName}</TableCell>
                    <TableCell>
                      <Badge variant="outline">
                        {request.bloodType}{request.rhFactor}
                      </Badge>
                    </TableCell>
                    <TableCell>{request.unitsRequested}</TableCell>
                    <TableCell>
                      <UrgencyBadge urgency={request.urgency} />
                    </TableCell>
                    <TableCell>{request.hospitalName}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function cn(...classes: (string | boolean | undefined)[]) {
  return classes.filter(Boolean).join(" ");
}

function StatusBadge({ status }: { status: string }) {
  const colors: Record<string, string> = {
    COLLECTED: "bg-blue-100 text-blue-800",
    TESTED: "bg-yellow-100 text-yellow-800",
    APPROVED: "bg-green-100 text-green-800",
    REJECTED: "bg-red-100 text-red-800",
    EXPIRED: "bg-gray-100 text-gray-800",
  };
  return (
    <span className={`inline-flex items-center rounded-full px-2 py-1 text-xs font-medium ${colors[status] || "bg-gray-100 text-gray-800"}`}>
      {status}
    </span>
  );
}

function UrgencyBadge({ urgency }: { urgency: string }) {
  const colors: Record<string, string> = {
    NORMAL: "bg-blue-100 text-blue-800",
    URGENT: "bg-orange-100 text-orange-800",
    EMERGENCY: "bg-red-100 text-red-800",
  };
  return (
    <span className={`inline-flex items-center rounded-full px-2 py-1 text-xs font-medium ${colors[urgency] || "bg-gray-100 text-gray-800"}`}>
      {urgency}
    </span>
  );
}
