// src/app/(dashboard)/donors/[id]/page.tsx
import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/db";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ArrowLeft } from "lucide-react";

export default async function DonorDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const donor = await prisma.donor.findUnique({
    where: { id },
    include: { donations: { orderBy: { donationDate: "desc" } } },
  });

  if (!donor) notFound();

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link href="/donors">
          <Button variant="outline" size="sm">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back
          </Button>
        </Link>
        <div>
          <h1 className="text-3xl font-bold">
            {donor.firstName} {donor.lastName}
          </h1>
          <p className="text-muted-foreground">Donor Profile</p>
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Personal Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <InfoRow label="Blood Type" value={`${donor.bloodType}${donor.rhFactor}`} />
            <InfoRow label="Gender" value={donor.gender} />
            <InfoRow label="Date of Birth" value={new Date(donor.dateOfBirth).toLocaleDateString()} />
            <InfoRow label="Phone" value={donor.phone} />
            <InfoRow label="Email" value={donor.email || "N/A"} />
            <InfoRow label="Address" value={`${donor.address}, ${donor.city}, ${donor.state} ${donor.zipCode}`} />
            <InfoRow label="Status" value={donor.status} />
            <InfoRow
              label="Last Donation"
              value={donor.lastDonation ? new Date(donor.lastDonation).toLocaleDateString() : "Never"}
            />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Donation Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-4">
              <div className="rounded-lg bg-red-50 p-4 text-center">
                <div className="text-3xl font-bold text-red-600">{donor.donations.length}</div>
                <div className="text-sm text-muted-foreground">Total Donations</div>
              </div>
              <div className="rounded-lg bg-red-50 p-4 text-center">
                <div className="text-3xl font-bold text-red-600">
                  {donor.donations.reduce((sum, d) => sum + d.volumeMl, 0)}
                </div>
                <div className="text-sm text-muted-foreground">Total mL Donated</div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Donation History</CardTitle>
        </CardHeader>
        <CardContent>
          {donor.donations.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">No donations recorded yet.</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead>Blood Type</TableHead>
                  <TableHead>Volume (mL)</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Collected By</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {donor.donations.map((donation) => (
                  <TableRow key={donation.id}>
                    <TableCell>
                      {new Date(donation.donationDate).toLocaleDateString()}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="font-mono">
                        {donation.bloodType}{donation.rhFactor}
                      </Badge>
                    </TableCell>
                    <TableCell>{donation.volumeMl}</TableCell>
                    <TableCell>
                      <Badge
                        variant={donation.status === "APPROVED" ? "default" : "outline"}
                      >
                        {donation.status}
                      </Badge>
                    </TableCell>
                    <TableCell>{donation.collectedBy}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between">
      <span className="text-sm text-muted-foreground">{label}</span>
      <span className="text-sm font-medium">{value}</span>
    </div>
  );
}

// pages/donors/[id].vue
<script setup lang="ts">
definePageMeta({ layout: "dashboard" });

const route = useRoute();
const { data: donor } = await useFetch(`/api/donors/${route.params.id}`);

const formatDate = (date: string | null) => {
  if (!date) return "N/A";
  return new Date(date).toLocaleDateString();
};
</script>

<template>
  <div class="max-w-3xl" v-if="donor">
    <div class="flex items-center gap-3 mb-6">
      <NuxtLink to="/donors" class="text-gray-400 hover:text-gray-600 text-sm">&larr; Back to Donors</NuxtLink>
    </div>

    <div class="bg-white rounded-xl border p-6 mb-6">
      <div class="flex items-center justify-between mb-4">
        <h1 class="text-xl font-bold text-gray-900">{{ donor.firstName }} {{ donor.lastName }}</h1>
        <span class="px-3 py-1 bg-red-50 text-red-700 rounded-lg text-sm font-medium border border-red-200">
          {{ donor.bloodType }}{{ donor.rhFactor }}
        </span>
      </div>

      <div class="grid grid-cols-2 gap-4 text-sm">
        <div><span class="text-gray-500">Gender:</span> {{ donor.gender }}</div>
        <div><span class="text-gray-500">Date of Birth:</span> {{ formatDate(donor.dateOfBirth) }}</div>
        <div><span class="text-gray-500">Email:</span> {{ donor.email || 'N/A' }}</div>
        <div><span class="text-gray-500">Phone:</span> {{ donor.phone }}</div>
        <div><span class="text-gray-500">Address:</span> {{ donor.address }}, {{ donor.city }}, {{ donor.state }} {{ donor.zipCode }}</div>
        <div><span class="text-gray-500">Status:</span>
          <span class="px-2 py-0.5 rounded text-xs font-medium ml-1"
            :class="{
              'bg-green-100 text-green-700': donor.status === 'ACTIVE',
              'bg-gray-100 text-gray-600': donor.status === 'INACTIVE',
              'bg-yellow-100 text-yellow-700': donor.status === 'DEFERRED',
            }">{{ donor.status }}</span>
        </div>
        <div><span class="text-gray-500">Last Donation:</span> {{ formatDate(donor.lastDonation) }}</div>
      </div>
    </div>

    <div class="bg-white rounded-xl border">
      <div class="p-4 border-b">
        <h2 class="font-medium text-sm">Donation History ({{ donor.donations?.length ?? 0 }})</h2>
      </div>
      <div v-if="donor.donations?.length" class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-gray-50 border-b">
            <tr>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Date</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Volume</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Status</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">Collected By</th>
            </tr>
          </thead>
          <tbody class="divide-y">
            <tr v-for="d in donor.donations" :key="d.id" class="hover:bg-gray-50">
              <td class="px-4 py-3">{{ formatDate(d.donationDate) }}</td>
              <td class="px-4 py-3">{{ d.volumeMl }} mL</td>
              <td class="px-4 py-3">
                <span class="px-2 py-0.5 rounded text-xs font-medium"
                  :class="{
                    'bg-yellow-100 text-yellow-700': d.status === 'COLLECTED',
                    'bg-blue-100 text-blue-700': d.status === 'TESTED',
                    'bg-green-100 text-green-700': d.status === 'APPROVED',
                    'bg-red-100 text-red-700': d.status === 'REJECTED',
                  }">{{ d.status }}</span>
              </td>
              <td class="px-4 py-3 text-gray-600">{{ d.collectedBy }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div v-else class="p-8 text-center text-gray-400 text-sm">No donations recorded.</div>
    </div>
  </div>
</template>
